

# the original templates from the CLIP paper

CLIP_IMAGENET_TEMPLATES = [
    'a bad photo of a {}.',
    'a photo of many {}.',
    'a sculpture of a {}.',
    'a photo of the hard to see {}.',
    'a low resolution photo of the {}.',
    'a rendering of a {}.',
    'graffiti of a {}.',
    'a bad photo of the {}.',
    'a cropped photo of the {}.',
    'a tattoo of a {}.',
    'the embroidered {}.',
    'a photo of a hard to see {}.',
    'a bright photo of a {}.',
    'a photo of a clean {}.',
    'a photo of a dirty {}.',
    'a dark photo of the {}.',
    'a drawing of a {}.',
    'a photo of my {}.',
    'the plastic {}.',
    'a photo of the cool {}.',
    'a close-up photo of a {}.',
    'a black and white photo of the {}.',
    'a painting of the {}.',
    'a painting of a {}.',
    'a pixelated photo of the {}.',
    'a sculpture of the {}.',
    'a bright photo of the {}.',
    'a cropped photo of a {}.',
    'a plastic {}.',
    'a photo of the dirty {}.',
    'a jpeg corrupted photo of a {}.',
    'a blurry photo of the {}.',
    'a photo of the {}.',
    'a good photo of the {}.',
    'a rendering of the {}.',
    'a {} in a video game.',
    'a photo of one {}.',
    'a doodle of a {}.',
    'a close-up photo of the {}.',
    'a photo of a {}.',
    'the origami {}.',
    'the {} in a video game.',
    'a sketch of a {}.',
    'a doodle of the {}.',
    'a origami {}.',
    'a low resolution photo of a {}.',
    'the toy {}.',
    'a rendition of the {}.',
    'a photo of the clean {}.',
    'a photo of a large {}.',
    'a rendition of a {}.',
    'a photo of a nice {}.',
    'a photo of a weird {}.',
    'a blurry photo of a {}.',
    'a cartoon {}.',
    'art of a {}.',
    'a sketch of the {}.',
    'a embroidered {}.',
    'a pixelated photo of a {}.',
    'itap of the {}.',
    'a jpeg corrupted photo of the {}.',
    'a good photo of a {}.',
    'a plushie {}.',
    'a photo of the nice {}.',
    'a photo of the small {}.',
    'a photo of the weird {}.',
    'the cartoon {}.',
    'art of the {}.',
    'a drawing of the {}.',
    'a photo of the large {}.',
    'a black and white photo of a {}.',
    'the plushie {}.',
    'a dark photo of a {}.',
    'itap of a {}.',
    'graffiti of the {}.',
    'a toy {}.',
    'itap of my {}.',
    'a photo of a cool {}.',
    'a photo of a small {}.',
    'a tattoo of the {}.',
]

CLIP_CALTECH_TEMPLATES = [
    'a photo of a {}.',
    'a painting of a {}.',
    'a plastic {}.',
    'a sculpture of a {}.',
    'a sketch of a {}.',
    'a tattoo of a {}.',
    'a toy {}.',
    'a rendition of a {}.',
    'a embroidered {}.',
    'a cartoon {}.',
    'a {} in a video game.',
    'a plushie {}.',
    'a origami {}.',
    'art of a {}.',
    'graffiti of a {}.',
    'a drawing of a {}.',
    'a doodle of a {}.',
    'a photo of the {}.',
    'a painting of the {}.',
    'the plastic {}.',
    'a sculpture of the {}.',
    'a sketch of the {}.',
    'a tattoo of the {}.',
    'the toy {}.',
    'a rendition of the {}.',
    'the embroidered {}.',
    'the cartoon {}.',
    'the {} in a video game.',
    'the plushie {}.',
    'the origami {}.',
    'art of the {}.',
    'graffiti of the {}.',
    'a drawing of the {}.',
    'a doodle of the {}.',
]

CLIP_DTD_TEMPLATES = [
    'a photo of a {} texture.',
    'a photo of a {} pattern.',
    'a photo of a {} thing.',
    'a photo of a {} object.',
    'a photo of the {} texture.',
    'a photo of the {} pattern.',
    'a photo of the {} thing.',
    'a photo of the {} object.',
]

CLIP_EUROSAT_TEMPLATES = [
    'a centered satellite photo of {}.',
    'a centered satellite photo of a {}.',
    'a centered satellite photo of the {}.',
]

CLIP_FGVC_TEMPLATES = [
    'a photo of a {}, a type of aircraft.',
    'a photo of the {}, a type of aircraft.',
]

CLIP_FLOWERS_TEMPLATES = [
    'a photo of a {}, a type of flower.',
]

CLIP_FOOD101_TEMPLATES = [
    'a photo of {}, a type of food.',
]

CLIP_OXFORD_PETS_TEMPLATES = [
    'a photo of a {}, a type of pet.',
]

CLIP_SUN397_TEMPLATES = [
    'a photo of a {}.',
    'a photo of the {}.',
]

CLIP_STANDFORD_CARS_TEMPLATES = [
    'a photo of a {}.',
    'a photo of the {}.',
    'a photo of my {}.',
    'i love my {}!',
    'a photo of my dirty {}.',
    'a photo of my clean {}.',
    'a photo of my new {}.',
    'a photo of my old {}.',
]

CLIP_UCF101_TEMPLATES = [
    'a photo of a person {}.',
    'a video of a person {}.',
    'a example of a person {}.',
    'a demonstration of a person {}.',
    'a photo of the person {}.',
    'a video of the person {}.',
    'a example of the person {}.',
    'a demonstration of the person {}.',
    'a photo of a person using {}.',
    'a video of a person using {}.',
    'a example of a person using {}.',
    'a demonstration of a person using {}.',
    'a photo of the person using {}.',
    'a video of the person using {}.',
    'a example of the person using {}.',
    'a demonstration of the person using {}.',
    'a photo of a person doing {}.',
    'a video of a person doing {}.',
    'a example of a person doing {}.',
    'a demonstration of a person doing {}.',
    'a photo of the person doing {}.',
    'a video of the person doing {}.',
    'a example of the person doing {}.',
    'a demonstration of the person doing {}.',
    'a photo of a person during {}.',
    'a video of a person during {}.',
    'a example of a person during {}.',
    'a demonstration of a person during {}.',
    'a photo of the person during {}.',
    'a video of the person during {}.',
    'a example of the person during {}.',
    'a demonstration of the person during {}.',
    'a photo of a person performing {}.',
    'a video of a person performing {}.',
    'a example of a person performing {}.',
    'a demonstration of a person performing {}.',
    'a photo of the person performing {}.',
    'a video of the person performing {}.',
    'a example of the person performing {}.',
    'a demonstration of the person performing {}.',
    'a photo of a person practicing {}.',
    'a video of a person practicing {}.',
    'a example of a person practicing {}.',
    'a demonstration of a person practicing {}.',
    'a photo of the person practicing {}.',
    'a video of the person practicing {}.',
    'a example of the person practicing {}.',
    'a demonstration of the person practicing {}.',
]


# augment the ones with too few templates
AUGMENTED_EUROSAT_TEMPLATES = [
    'a satellite photo of {}.',
    'a satellite photo of a {}.',
    'a satellite photo of the {}.',
    'a centered satellite view of {}.',
    'an overhead satellite image of {}.',
    'a detailed satellite shot of {}.',
    'a satellite photograph focusing on {}.',
    'a top-down satellite capture of {}.',
    'a satellite image showcasing {}.',
    'a high-resolution satellite photo of {}.',
    'a clear satellite image of {}.',
    'a satellite perspective of {}.',
    'a satellite snapshot of {}.'
]

AUGMENTED_FGVC_TEMPLATES = [
    'a photo of a {}, a type of aircraft.',
    'a photo of the {}, a type of aircraft.',
    'a photo of a {}, a type of Boeing aircraft.',
    'a photo of the {}, a type of Airbus plane.',
    'a photo of a {}, an aircraft on the runway.',
    'a photo of the {}, a military aircraft in flight.',
    'a photo of a {}, a twin-engine plane.',
    'a photo of the {}, a commercial airliner.',
    'a photo of a {}, a private jet.',
    'a photo of the {}, an aircraft during takeoff.',
    'a photo of a {}, a fighter jet.',
    'a photo of the {}, an aircraft on a military mission.'
]

AUGMENTED_FLOWERS_TEMPLATES = [
    'a photo of a {}, a type of flower.',
    'a photo of a {}, a type of flower in a garden.',
    'a photo of a {}, a type of wildflower.',
    'a photo of a {}, a type of flower in a field.',
    'a photo of a {}, a type of flower by the roadside.',
    'a photo of a {}, a type of flower in a pot.',
    'a photo of a {}, a colorful type of flower.',
    'a photo of a {}, a fragrant type of flower.',
    'a photo of a {}, a single bloom of a flower.',
    'a photo of a {}, a flower in full bloom.',
    'a photo of a {}, a type of flower in a bouquet.'
]

AUGMENTED_FOOD101_TEMPLATES = [
    'a photo of {}, a type of food.',
    'a photo of {}, a type of food served on a plate.',
    'a photo of {}, a type of street food.',
    'a photo of {}, a type of food in a bowl.',
    'a photo of {}, a savory dish.',
    'a photo of {}, a sweet treat.',
    'a photo of {}, a type of food at a restaurant.',
    'a photo of {}, a home-cooked meal.',
    'a photo of {}, a healthy option.',
    'a photo of {}, a traditional cuisine.',
    'a photo of {}, a type of food in a gourmet presentation.'
]

AUGMENTED_OXFORD_PETS_TEMPLATES = [
    'a photo of a {}, a type of pet.',
    'a photo of a {}, a type of pet in a home.',
    'a photo of a {}, a type of pet in a garden.',
    'a photo of a {}, a type of pet at a park.',
    'a photo of a {}, a type of pet in a pet bed.',
    'a photo of a {}, a fluffy pet.',
    'a photo of a {}, a small pet.',
    'a photo of a {}, a playful pet.',
    'a photo of a {}, a lazy pet.',
    'a photo of a {}, a type of pet playing.',
    'a photo of a {}, a type of pet sleeping.'
]

AUGMENTED_SUN397_TEMPLATES = [
    'a photo of a {}.',
    'a photo of the {}.',
    'a photo of a {}, at sunset.',
    'a photo of the {}, on a rainy day.',
    'a photo of a {}, during winter.',
    'a photo of the {}, under a clear sky.',
    'a photo of a {}, with people walking.',
    'a photo of the {}, with children playing.',
    'a photo of a {}, with colorful flowers.',
    'a photo of the {}, with tall buildings.',
    'a photo of a {}, an aerial view.',
    'a photo of the {}, a close-up shot.'
]

AUGMENTED_STANDFORD_CARS_TEMPLATES = [
    'a photo of a {}.',
    'a photo of the {}.',
    'a photo of my {}.',
    'i love my {}!',
    'a photo of my dirty {}.',
    'a photo of my clean {}.',
    'a photo of my new {}.',
    'a photo of my old {}.',
    'a photo of a {}, in a garage.',
    'a photo of the {}, on the road.',
    'a photo of my {}, at a car show.',
    'i love my {}, especially on road trips!',
    'a photo of my dirty {}, after a muddy adventure.',
    'a photo of my clean {}, after a car wash.',
    'a photo of my new {}, parked in the driveway.',
    'a photo of my old {}, still running great.',
    'a photo of a {}, during a road trip.',
    'a photo of the {}, while racing.'
]


IMAGENET_A_IDX = [6, 11, 13, 15, 17, 22, 23, 27, 30, 37, 39, 42, 47, 50, 57, 70, 71, 76, 79, 89, 90, 94, 96, 97, 99, 105, 107, 108, 110, 113, 124, 125, 130, 132, 143, 144, 150, 151, 207, 234, 235, 254, 277, 283, 287, 291, 295, 298, 301, 306, 307, 308, 309, 310, 311, 313, 314, 315, 317, 319, 323, 324, 326, 327, 330, 334, 335, 336, 347, 361, 363, 372, 378, 386, 397, 400, 401, 402, 404, 407, 411, 416, 417, 420, 425, 428, 430, 437, 438, 445, 456, 457, 461, 462, 470, 472, 483, 486, 488, 492, 496, 514, 516, 528, 530, 539, 542, 543, 549, 552, 557, 561, 562, 569, 572, 573, 575, 579, 589, 606, 607, 609, 614, 626, 627, 640, 641, 642, 643, 658, 668, 677, 682, 684, 687, 701, 704, 719, 736, 746, 749, 752, 758, 763, 765, 768, 773, 774, 776, 779, 780, 786, 792, 797, 802, 803, 804, 813, 815, 820, 823, 831, 833, 835, 839, 845, 847, 850, 859, 862, 870, 879, 880, 888, 890, 897, 900, 907, 913, 924, 932, 933, 934, 937, 943, 945, 947, 951, 954, 956, 957, 959, 971, 972, 980, 981, 984, 986, 987, 988]
IMAGENET_R_IDX = [1, 2, 4, 6, 8, 9, 11, 13, 22, 23, 26, 29, 31, 39, 47, 63, 71, 76, 79, 84, 90, 94, 96, 97, 99, 100, 105, 107, 113, 122, 125, 130, 132, 144, 145, 147, 148, 150, 151, 155, 160, 161, 162, 163, 171, 172, 178, 187, 195, 199, 203, 207, 208, 219, 231, 232, 234, 235, 242, 245, 247, 250, 251, 254, 259, 260, 263, 265, 267, 269, 276, 277, 281, 288, 289, 291, 292, 293, 296, 299, 301, 308, 309, 310, 311, 314, 315, 319, 323, 327, 330, 334, 335, 337, 338, 340, 341, 344, 347, 353, 355, 361, 362, 365, 366, 367, 368, 372, 388, 390, 393, 397, 401, 407, 413, 414, 425, 428, 430, 435, 437, 441, 447, 448, 457, 462, 463, 469, 470, 471, 472, 476, 483, 487, 515, 546, 555, 558, 570, 579, 583, 587, 593, 594, 596, 609, 613, 617, 621, 629, 637, 657, 658, 701, 717, 724, 763, 768, 774, 776, 779, 780, 787, 805, 812, 815, 820, 824, 833, 847, 852, 866, 875, 883, 889, 895, 907, 928, 931, 932, 933, 934, 936, 937, 943, 945, 947, 948, 949, 951, 953, 954, 957, 963, 965, 967, 980, 981, 983, 988]

FOOD101_POST_SENTENCES = [
    "The food looks crispy.",
    "It appears to be freshly baked.",
    "The texture is creamy.",
    "It has a glossy coating.",
    "The surface is charred.",
    "It looks juicy.",
    "The food is garnished with herbs.",
    "It has a crunchy exterior.",
    "The interior looks tender.",
    "The food is covered in sauce.",
    "It has a golden-brown crust.",
    "The texture is flaky.",
    "It is topped with melted cheese.",
    "The food appears to be marinated.",
    "It has a vibrant color.",
    "The surface is sprinkled with seasoning.",
    "It looks savory.",
    "The food is wrapped in a leaf.",
    "It has a smooth texture.",
    "The food is stuffed.",
    "It looks well-cooked.",
    "The surface is glazed.",
    "It has a rich aroma.",
    "The food appears to be grilled.",
    "It has a light, airy texture.",
    "The surface is caramelized.",
    "It looks moist.",
    "The food is topped with nuts.",
    "It has a spicy kick.",
    "The food is dusted with powdered sugar.",
    "It has a tender crumb.",
    "The surface is frosted.",
    "It looks doughy.",
    "The food is encrusted with seeds.",
    "It has a chewy texture.",
    "The surface is golden and crispy.",
    "It looks piping hot.",
    "The food is served with a dipping sauce.",
    "It has a layered structure.",
    "The texture is silky.",
    "It is drizzled with honey.",
    "The food is packed with fillings.",
    "It has a tangy flavor.",
    "The surface is slightly charred.",
    "It looks plump and juicy.",
    "The food is sprinkled with cheese.",
    "It has a smooth, velvety texture.",
    "The surface is studded with dried fruits.",
    "It looks caramelized.",
    "The food is topped with fresh berries.",
    "It has a smoky flavor.",
    "The texture is dense and moist.",
    "It is wrapped in a crispy shell.",
    "The food is served on a skewer.",
    "It has a thick, creamy filling.",
    "The surface is sprinkled with coarse salt.",
    "It looks light and fluffy.",
    "The food is layered with sauce.",
    "It looks crispy.",
    "It appears baked.",
    "The texture is creamy.",
    "It is glossy.",
    "The surface is charred.",
    "It looks juicy.",
    "Garnished with herbs.",
    "Crunchy exterior.",
    "Tender interior.",
    "Covered in sauce.",
    "Golden crust.",
    "Flaky texture.",
    "Topped with cheese.",
    "Marinated.",
    "Vibrant color.",
    "Sprinkled with seasoning.",
    "Looks savory.",
    "Wrapped in a leaf.",
    "Smooth texture.",
    "Stuffed.",
    "Well-cooked.",
    "Glazed surface.",
    "Rich aroma.",
    "Grilled.",
    "Airy texture.",
    "Caramelized surface.",
    "Looks moist.",
    "Topped with nuts.",
    "Spicy kick."
]

DEFAULT_POST_SENTENCES = [
    ""
    "The scene appears to have been captured outside.",
    "The subject seems to be in a worn-out state.",
    "The lighting suggests it was taken during the golden hour.",
    "The subject is off-center, drawing the viewer's eye to the background.",
    "There is a distinct object placed next to the subject.",
    "It appears to be in motion.",
    "It might be looking to the right.",
    "They appear to be looking towards the left.",
    "It appears to be looking directly at the camera.",
    "The subject is in a relaxed pose.",
    "The background includes a noticeable structure.",
    "A tree can be seen in the background.",
    "The subject is in a dynamic pose.",
    "The human subject is wearing a hat.",
    "The human is wearing sunglasses.",
    "The scene appears to be in a rural area.",
    "The scene looks nice and clean.",
    "The house in the background is very modern.",
    "The sofa in the background is very old.",
    "The toy in the background is very colorful.",
    "The scene appears to have been captured at night.",
    "The subject seems to be brand new.",
    "The lighting suggests it was taken indoors.",
    "The subject is centered in the frame, drawing immediate focus.",
    "There is another similar object close to the subject.",
    "It appears to be stationary.",
    "It might be looking to the left.",
    "They appear to be looking upwards.",
    "It appears to be looking away from the camera.",
    "The subject is in an alert pose.",
    "The background includes a visible horizon.",
    "A car can be seen in the background.",
    "The subject is in a static pose.",
    "The human subject is holding an object.",
    "The human is smiling.",
    "The scene appears to be in an urban area.",
    "The scene looks cluttered and busy.",
    "The building in the background is very old.",
    "The chair in the background is very modern.",
    "The painting in the background is very abstract.",
    "The scene is indoors.",
    "The subject is new.",
    "The lighting is dim.",
    "The subject is in focus.",
    "A person is nearby.",
    "It is static.",
    "It faces left.",
    "They look down.",
    "It looks up.",
    "The subject is active.",
    "A mountain is visible.",
    "A dog is in the background.",
    "The subject is sitting.",
    "The person is walking.",
    "The person is laughing.",
    "The scene is suburban.",
    "The area is tidy.",
    "The building is ancient.",
    "The table is modern.",
    "The subject is partially obscured.",
    "There are multiple similar objects around.",
    "The lighting is natural.",
    "The background is blurred.",
    "A person is holding the subject.",
    "It is slightly tilted.",
    "It faces forward.",
    "They are grouped together.",
    "It looks straight ahead.",
    "The subject is standing.",
    "The background is plain.",
    "A shadow is visible.",
    "The subject is in motion.",
    "The person is wearing casual clothes.",
    "The person is sitting down.",
    "The scene is busy.",
    "The area is well-lit.",
    "The background is urban.",
    "The setting is a park.",
    "The surface appears smooth.",
    "The object looks rough.",
    "The texture is glossy.",
    "The material seems soft.",
    "The surface is reflective.",
    "The texture is matte.",
    "It appears to be made of wood.",
    "The subject looks metallic.",
    "The object is fuzzy.",
    "The texture is grainy.",
    "The surface seems to be cracked.",
    "It has a bumpy texture.",
    "The material looks shiny.",
    "The object has a sleek surface.",
    "The texture appears velvety.",
    "The surface is uneven.",
    "The material looks coarse.",
    "The object has a smooth finish.",
    "The surface is pebbled.",
    "The scene includes a body of water.",
    "The background is a dense forest.",
    "The setting is a desert.",
    "The subject is near a lake.",
    "The background shows a mountain range.",
    "The scene is at a beach.",
    "The area is covered in snow.",
    "The subject is in a jungle.",
    "The scene is near a river.",
    "The background is a vast plain.",
    "The setting is a rainforest.",
    "The scene includes a waterfall.",
    "The background shows rolling hills.",
    "The subject is in a savannah.",
    "The area is rocky.",
    "The scene is in a canyon.",
    "The background is a cityscape.",
    "The subject is near a pond.",
    "The setting is an arctic tundra.",
    "A smartphone is visible.",
    "The subject is a small gadget.",
    "The object appears to be a watch.",
    "The scene includes a laptop.",
    "The background shows a tablet.",
    "There is a camera in the scene.",
    "The subject is a pair of earbuds.",
    "A charger is visible nearby.",
    "The object is a compact speaker.",
    "The subject is a keychain.",
    "The scene includes a remote control.",
    "There is a pen next to the subject.",
    "A small drone is visible.",
    "The object is a USB drive.",
    "The subject is a small clock.",
    "The background includes a set of headphones.",
    "There is a gaming console in the scene.",
    "A smartwatch is visible on the subject.",
    "The object is a small flashlight.",
    "The scene is at a wedding.",
    "The subject is at a birthday party.",
    "The event is a concert.",
    "The scene shows a festival.",
    "The background is a sports event.",
    "The subject is at a conference.",
    "The scene is during a parade.",
    "The event is a graduation ceremony.",
    "The subject is at a fair.",
    "The scene shows a protest.",
    "The event is a carnival.",
    "The subject is at a market.",
    "The scene is during a meeting.",
    "The event is a family gathering.",
    "The subject is at a gala.",
    "The scene shows a workshop.",
    "The event is a theater performance.",
    "The subject is at a book signing.",
    "The scene is during a competition.",
    "The object is prominently featured.",
    "A book is in the foreground.",
    "A cup is placed nearby.",
    "A toy is lying on the ground.",
    "The object is an intricate sculpture.",
    "A painting is hanging on the wall.",
    "A chair is next to the main item.",
    "The object is an old clock.",
    "A lamp is casting light on it.",
    "A piece of jewelry is displayed.",
    "A vase is filled with flowers.",
    "A bicycle is leaning against a wall.",
    "A hat is resting on the table.",
    "A mirror reflects the scene.",
    "A small figurine is part of the display.",
    "A pair of shoes is neatly placed.",
    "A bag is hanging on a hook.",
    "A computer is part of the setup.",
    "A plant is growing nearby.",
    "A candle is burning softly.",
    "A framed photo is on display.",
    "A notebook lies open.",
    "A guitar is propped in the corner.",
    "A clock is ticking away.",
    "A bottle is standing upright.",
    "A pencil is resting on the desk.",
    "A set of keys is on the counter.",
    "A basket is filled with fruits.",
    "A pair of glasses is left open.",
    "A remote control is on the armrest.",
    "A newspaper is folded neatly.",
    "A pillow is propped up.",
    "A blanket is draped over a chair.",
    "A toy car is positioned on the floor.",
    "A calendar is marked with dates.",
    "A picture frame sits on the shelf.",
    "A potted plant is in the corner.",
    "A water bottle is half-full.",
    "A clock is hung on the wall.",
    "A calculator is next to the papers.",
    "A pair of scissors is on the table.",
    "A stapler is beside the documents.",
    "A mouse pad is under the mouse.",
    "A light switch is on the wall.",
    "A doormat is at the entrance.",
    "A map is pinned to the board.",
    "A coaster is under the cup.",
    "A screwdriver is lying on the bench.",
    "The object is centered in the frame.",
    "It is positioned at the edge of the table.",
    "The object is hanging from the ceiling.",
    "It is mounted on the wall.",
    "The object is placed on the shelf.",
    "It is leaning against the wall.",
    "The object is tucked in a corner.",
    "It is situated under the desk.",
    "The object is lying on the floor.",
    "It is placed beside the window.",
    "The object is perched on a ledge.",
    "It is balanced on the armrest.",
    "The object is nestled in a drawer.",
    "It is suspended in mid-air.",
    "The object is standing upright.",
    "It is positioned near the door.",
    "The object is floating in the water.",
    "It is arranged in a neat row.",
    "The object is stacked on top of others.",
    "It is hidden behind a curtain.",
    "The object is wedged between books.",
    "It is displayed on a pedestal.",
    "The object is lying flat.",
    "It is propped up against a cushion.",
    "The object is resting on a pillow.",
    "It is placed in the center of the room.",
    "The object is dangling from a string.",
    "It is fixed to the ground.",
    "The object is placed at an angle.",
    "The object is brightly colored.",
    "It has a shiny surface.",
    "The object is covered in patterns.",
    "It appears to be brand new.",
    "The object looks worn out.",
    "It has a sleek design.",
    "The object is transparent.",
    "It has a rustic look.",
    "The object is intricately detailed.",
    "It has a smooth finish.",
    "The object is oddly shaped.",
    "It has a vintage style.",
    "The object is glossy.",
    "It has a matte texture.",
    "The object is multi-colored.",
    "It has a minimalist design.",
    "The object looks futuristic.",
    "It has a rugged appearance.",
    "The object is small and delicate.",
    "It has an elegant look.",
    "The object is bulky.",
    "It has a soft texture.",
    "The object is highly polished.",
    "It has a dull finish.",
    "The object is monochrome.",
    "It has a rough surface.",
    "The object is translucent.",
    "It has a geometric pattern.",
    "The object is finely crafted.",
    "There are several of them.",
    "Multiple objects are clustered together.",
    "They are scattered across the area.",
    "A pair of objects is visible.",
    "They are arranged in a row.",
    "The objects are stacked on top of each other.",
    "There are duplicates of the same item.",
    "A few objects are grouped closely.",
    "They are spread out evenly.",
    "A collection of objects is displayed.",
    "There are numerous items.",
    "The objects are organized neatly.",
    "They are piled up haphazardly.",
    "Several objects are lined up.",
    "A variety of objects is present.",
    "The objects are evenly spaced.",
    "There is a handful of them.",
    "They are arranged in a pattern.",
    "A couple of objects are placed side by side.",
    "Many objects are scattered around.",
    "The objects form a cluster.",
    "A set of objects is visible.",
    "They are grouped in pairs.",
    "The objects are laid out randomly.",
    "A series of objects is aligned.",
    "They are placed in a circular arrangement.",
    "A number of objects are in a pile.",
    "The objects are distributed sparsely.",
    "Several items are positioned closely together.",
    "They are arranged symmetrically.",
    "A trio of objects is present.",
    "They are positioned in a triangular formation.",
    "The objects are clustered in one area.",
    "There are a multitude of items.",
    "The objects are distributed evenly.",
    "A pair of identical objects is seen.",
    "The objects are interspersed randomly.",
    "They are grouped into sets.",
    "Several objects form a line.",
    "They are gathered in a heap.",
    "A collection of similar items is visible.",
    "The objects are placed at intervals.",
    "Several objects are arranged in a grid.",
    "They are positioned in a semi-circle.",
    "Multiple objects create a pattern.",
    "They are scattered across the surface.",
    "A few objects are positioned randomly.",
    "The objects are distributed in a haphazard manner.",
    "Several objects are aligned perfectly.",
    "They are clustered near each other.",
    "The objects are spread across the table.",
    "A couple of items are positioned next to each other.",
    "They are stacked in a column.",
    "Several objects are displayed in a showcase.",
    "They are scattered throughout the scene.",
    "A few items are grouped together.",
    "The objects form a random cluster.",
    "They are positioned in rows and columns.",
]
